name: Publish Docker Container
on: [push]
jobs:
  Build:
    name: Create and Push Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.11
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publish Docker Image
        run: |
          docker build -t ghcr.io/fairdatapipeline/rsecon:latest .
          docker push ghcr.io/fairdatapipeline/rsecon:latest
