name: Publish Docker Container
on: [push]
jobs:
  Build:
    name: Create and Push Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        with:
          install: true
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publish Docker Image
        run: |
          docker build -t ghcr.io/fairdatapipeline/aarm64-rsecon:latest .
          docker push ghcr.io/fairdatapipeline/aarm64-rsecon:latest
